platform :ios, '13.0'

target 'expoTest' do
  use_frameworks!
  use_modular_headers!

  # react-native-document-picker 추가
  pod 'react-native-document-picker', :path => '../node_modules/react-native-document-picker'
  pod 'react-native-webview', :path => '../node_modules/react-native-webview'


  post_install do |installer|
    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|
        target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
          resource_bundle_target.build_configurations.each do |config|
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
          end
        end
      end
  end

  post_integrate do |installer|
    begin

    rescue => e
      Pod::UI.warn e
    end
  end
end
