# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'expoTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'


end
